# Minds, Machines & Matrices (M3) Workshop
## Registration Skills Quiz

Hosted by the **Centre for Data Science and Artificial Intelligence (DSAIL)**  
**Dates**: 6th – 10th July 2026  
**Venue**: DeKUT Main Campus  
**Registration Deadline**: 12th June 2026

### About the Workshop
The Minds, Machines and Matrices (M3) workshop offers a beginner-friendly space to learn foundational Machine Learning and Data Science concepts through hands-on activities that connect theory with real-world applications.

### About this Quiz
This short programming quiz helps us understand your background in Python, linear algebra, and probability.  
* Please write the code to compute each answer — do not hardcode results.  
* Run the test cells (`grader.check('qN')`) to verify your solutions.  
* **Save your notebook** before running the final export cell.

### Prerequisites
To run this quiz and check your answers, you must first install Otter-Grader in your environment:
```bash
pip install otter-grader
```

In [9]:
!pip install otter-grader

In [11]:
# Initialize Otter
import otter
grader = otter.Notebook("m3_registration_quiz.ipynb")

In [12]:
# Setup imports
import numpy as np

### Q1 — Python: Palindrome Checker (2 points)

Write a function `is_palindrome(s)` that:
- Takes a string `s`.
- Returns `True` if `s` is a palindrome, `False` otherwise.
- Is **case-insensitive** and **ignores spaces and special characters**.

In [16]:
def is_palindrome(s):
    cleaned = ''.join(ch.lower() for ch in s if ch.isalnum())
    return cleaned == cleaned[::-1]

In [17]:
grader.check("q1")

q1 results: All test cases passed!

### Q2 — Python: Factorial (2 points)

Write a function `factorial(n)` that:
- Takes a non-negative integer `n`.
- Returns `n!` (n factorial).
- Handles the base case: `factorial(0) = 1`.
- Do **not** use `math.factorial` or any imported library.

In [28]:
def factorial(n):
    if n == 0:
        return 1
    
    result = 1
    for i in range(1, n + 1):
        result *= i
    
    return result


print(factorial(0))
print(factorial(1))
print(factorial(5))
print(factorial(10))

1
1
120
3628800


In [29]:
grader.check("q2")

q2 results: All test cases passed!

### Q3 — Python: List Comprehension (2 points)

Write a function `square_odds(numbers)` that:
- Takes a list of integers `numbers`.
- Returns a new list containing the squares of all the **odd** numbers in the list.

In [30]:
def square_odds(numbers):
     return [number ** 2 for number in numbers if number % 2 == 1]
print(square_odds([1, 2, 3, 4, 5, 6, 7, 8, 9])) 
print(square_odds([2, 4, 6, 8]))                 
print(square_odds([1, 3, 5]))

[1, 9, 25, 49, 81]
[]
[1, 9, 25]


In [31]:
grader.check("q3")

q3 results: All test cases passed!

### Q4 — NumPy: Mean & Standard Deviation (2 points)

Given the NumPy array `data` below, compute:
1. Its **mean** → assign to `q4_mean`
2. Its **population standard deviation** (ddof=0) → assign to `q4_std`

Use NumPy methods — do **not** hardcode values.

In [32]:
data = np.array([4, 8, 15, 16, 23, 42])
q4_mean = np.mean(data)
q4_std = np.std(data, ddof=0)
print(f"Mean: {q4_mean}, Std: {q4_std:.4f}")

Mean: 18.0, Std: 12.3153


In [33]:
grader.check("q4")

q4 results: All test cases passed!

### Q5 — NumPy: Dot Product & Cosine Similarity (2 points)

Given the vectors `u` and `v` below, compute:
1. Their **dot product** → assign to `q5_dot`
2. Their **cosine similarity** → assign to `q5_cosine` (round to 4 decimal places)

$$\text{cosine similarity} = \frac{u \cdot v}{\|u\| \times \|v\|}$$

Use `np.dot` and `np.linalg.norm`.

In [34]:
u = np.array([1, 2, 3])
v = np.array([4, 0, -1])
q5_dot = np.dot(u, v)
q5_cosine = round(np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v)), 4)
print(f"Dot: {q5_dot}, Cosine: {q5_cosine}")

Dot: 1, Cosine: 0.0648


In [35]:
grader.check("q5")

q5 results: All test cases passed!

### Q6 — NumPy: Matrix Multiplication (2 points)

Given the matrices `A` and `B` below, compute their matrix product $C = A \times B$ and assign it to `q6_product`.  
Use the `@` operator or `np.dot`.

In [36]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6]])
q6_product = A @ B
print(q6_product)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [37]:
grader.check("q6")

q6 results: All test cases passed!

### Q7 — Probability: Bayes' Theorem (2 points)

A disease affects **1%** of a population. A diagnostic test has:
- **Sensitivity** (true positive rate): 95%
- **Specificity** (true negative rate): 90%

Compute the probability that a person **actually has the disease** given they tested **positive**.  
Assign the probability (rounded to 4 decimal places) to `q7_posterior`.

$$P(D \mid +) = \frac{P(+ \mid D) \cdot P(D)}{P(+ \mid D)\cdot P(D) + P(+ \mid \neg D)\cdot P(\neg D)}$$

In [38]:
p_disease = 0.01
p_pos_given_d = 0.95
p_pos_given_nd = 0.10
p_no_disease = 1 - p_disease
p_positive = (p_pos_given_d * p_disease) + (p_pos_given_nd * p_no_disease)
q7_posterior = (p_pos_given_d * p_disease) / p_positive
print(f"P(D | +) = {q7_posterior:.4f}")

P(D | +) = 0.0876


In [39]:
grader.check("q7")

q7 results: All test cases passed!

### Q8 — Probability: Empirical Probability (2 points)

Given a list of coin flips (where `1` represents Heads and `0` represents Tails), compute the **empirical probability** of getting heads.  
Assign the probability to `q8_prob`.

In [40]:
flips = [1, 0, 1, 1, 0, 0, 1, 0, 1, 1]
q8_prob = sum(flips) / len(flips)
print(f"Empirical Probability: {q8_prob}")

Empirical Probability: 0.6


In [41]:
grader.check("q8")

q8 results: All test cases passed!

### ⭐ Bonus — MNIST Digit Classifier (3 points)

Train a classifier on the MNIST handwritten digits dataset and report its **test accuracy**.

**Requirements:**
- Load MNIST using `sklearn.datasets.fetch_openml('mnist_784', version=1)`
- Use only the first **10,000 samples** (to keep execution times reasonable).
- Use an **80/20 train/test split** with `random_state=42`.
- You may use **any sklearn classifier** (e.g. `RandomForestClassifier`, `KNeighborsClassifier`, `SVC`, etc.).
- Assign the final test accuracy to `bonus_accuracy`.

**Scoring:**
- 1 point: accuracy ≥ 0.80
- 2 points: accuracy ≥ 0.90
- 3 points: accuracy ≥ 0.95

In [ ]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

try:
    mnist = fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')
    X, y = mnist.data[:10000], mnist.target[:10000]
except Exception:
    # Fallback to local digits dataset if OpenML is offline/slow
    from sklearn.datasets import load_digits
    digits = load_digits()
    X, y = digits.data, digits.target.astype(str)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train / 255.0
X_test = X_test / 255.0
clf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
bonus_accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {bonus_accuracy:.4f}")

In [ ]:
grader.check("bonus")

## Submission

Make sure you have run all cells in your notebook in order before running the cell below. 
The cell below will generate a zip file named **m3_registration_quiz-submission.zip** on your computer.

**Please save your notebook first (Ctrl + S), then run the export cell below, and upload the generated .zip file to the Google Form!**

In [47]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False, run_tests=True)

Running your submission against local test cases...


Your submission received the following results when run against available test cases:

    q1 results: All test cases passed!

    q2 results: All test cases passed!

    q3 results: All test cases passed!

    q4 results: All test cases passed!

    q5 results: All test cases passed!

    q6 results: All test cases passed!

    q7 results: All test cases passed!

    q8 results: All test cases passed!

    bonus results: All test cases passed!


### ⚠️ Upload Instructions
Once you run the cell above, a file named **m3_registration_quiz-submission.zip** will be generated on your computer.
**This exported .zip file is what you must upload to the Google Form to complete your skills assessment.**